module.exports = {
    user: {
        USER_ADD: 'User Created Succesfully',
        UPDATE: 'User Updated Succesfully',
        FORGET_PASSWORD: 'Password Updated successfully',
        FORGET_PASSWORD_SENT_MAIL:'Password reset link sent to email',
        DELETE: 'User Deleted Succesfully',
        DELETED: 'User already Deleted Succesfully',
        READ: 'User Data Fetched Succesfully',
        READ_ERROR: 'User not Fetched',
        USER_LOGIN_SUCCESS: 'User login succesfully',
        FAILURE_CREATE: 'Unable to Create user',
        FAILURE_PASSWORD_UPDATE: 'Unable to Update password',
        FAILURE_UPDATE: 'Unable to Update user',
        FAILURE_DELETE: 'Unable to Delete user',
        USER_EXIST: 'User Already Exists',
        USER_NOT_EXIST: 'User Does Not Exists',
        ACTIVE_USER: 'only active user can login',
        WRONG_USERnAME_PASSWORD: 'Wrong Password',
        FORGET_PASSWORD_ERROR: "this password already have been used.",
        IMAGE: "image uploaded succesfuly",
        RESET_PASSWORD:'Password reset page',
        UPDATE_PASSWORD:"Password Updated Succesfully",
        FAILURE_RESET_PASSWORD:'Invalid reset token',
    },

    ADMIN_LOGIN: 'Login Succesfully',
    ADMIN_LOGIN_FAILURE: 'incorrect username and password',
    ADMIN_DOES_NOT_EXISTS: 'Admin Does Not Exists',
    PASSWORD_INCORRECT: 'Password entered is Incorrect',
    ADMIN_LOGOUT: 'Logout Succesfully',
    ADMIN_ALERT: 'First you need to login',
    
    CATCH_ERROR: 'Something went wrong',
};